config/routes.rb
Rails.application.routes.draw do
	root "blogs#all_blogs"
	get "archive" => "blogs#archive"

	# Resources for Blogs
  	resources :blogs

  	# Devise for Admin Login
  	devise_for :admins,
	path: '', path_names: { sign_in: 'login'}
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
	attr_accessor :image
	has_attached_file :image, styles: { medium: "500x500", thumb: "100x100" }
  	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
	helper_method :require_admin

	def require_admin
	    unless current_admin 
	  	  redirect_to root_path, error: "You Need to login first" 	
	    end	
	end 

  	def after_sign_in_path_for(resource)
	   	blogs_path
	end

  	def after_sign_out_path_for(resource)
	    new_session_path(resource_name)
	end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  def all_blogs
    @all_blogs = Blog.all.order(created_at: :desc)
  end

  def archive
    @all_archives = Blog.all.order(created_at: :desc).paginate(:page => params[:page], :per_page => 5)
  end

  def index
    @blogs = Blog.all.order(created_at: :desc)
  end

  def show
  end

  def new
    @blog = Blog.new
  end

  def edit
  end

  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to blogs_path, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to blogs_path, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :content, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(page_title = '')
		base_title = "Anime Blog"
		if page_title.empty?
			base_title
		else
			"#{page_title} - #{base_title}"
		end
	end 
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_form.html.erb
      <%= form_for(blog) do |f| %> 
        <label for="blog_image" class="form-title">EYE CATCH IMAGE
          <div class="form-file u-clear">
              <span class="form-file-button" for="blog_image">UPLOAD</span>
          </div>
        </label>
        <%= f.file_field :image, class: "input input-image" %>

        <%= f.label :title, "TITLE", class: "form-title" %>
        <div class="form-body">
          <%= f.text_field :title, class: "input input-text" %>
        </div>

        <%= f.label :content, "CONTENT", class: "form-title" %>
        <div class="form-textarea">
          <%= f.text_area :content, cols: "30", rows: "10", class: "input input-contents" %>
        </div>
        <label for="submit" class="form-button">
            <div class="button">
                <p class="button-text">Submit</p>
            </div>
        </label>
        <%= f.submit class: "input input-submit", id: "submit" %>
      <% end %>

app/views/blogs/all_blogs.html.erb
<% provide(:title, "All Blogs") %>
<%= render "partials/user_navbar" %>
<!--start l-contents-->
    <div class="l-container u-clear">

        <!--start l-main-->
        <main class="l-main js-main">
            <div class="l-main-block"></div>
            <div class="archive">
                <ul class="archive-list">
                    
                	<% @all_blogs.each do |blog| %>
                		<li class="archive-item">
	                    	<article class="card">
	                    		<%= link_to blog_path(blog), class: "card-link" do %>
	                    			<%= image_tag blog.image.url(:medium), alt: blog.title, class: "card-image" %>
	                    			<div class="card-bottom">
	                    				<h1 class="card-title"><%= blog.title %></h1>
							            <time class="card-date">
							                <%= blog.created_at.strftime("%d %b, %Y")%>
							            </time>
	                    			</div>
	                    		<% end %>
	                    	</article>
	                    </li>
                	<% end %> 
                    
                </ul>
            </div>
            <a href="#" class="archive-button">
                <div class="button">
				    <p class="button-text">More</p>
				</div>
            </a>
        </main>
        <!--end l-main-->

    </div>
    <!--end l-contents-->

app/views/blogs/archive.html.erb
<% provide(:title, "All Archives") %>
<%= render "partials/user_navbar" %>

<!--start l-contents-->
<div class="l-container u-clear">

    <!--start l-main-->
    <main class="l-main js-main">
        <div class="l-main-block"></div>
            <div class="page-number">
                Page <span ><%= @all_archives.current_page %>/<%= @all_archives.total_pages %></span>
            </div>
            <div class="archive">
                <ul class="archive-list">
                    <% @all_archives.each do |archive| %>
	                    <li class="archive-item">
	                        <article class="card">
	                            <a href="#" class="card-link">
	                            	<%= image_tag archive.image.url(:medium), alt: archive.title, class: "card-image" %>
	                                <div class="card-bottom">
	                                    <h1 class="card-title"><%= archive.title %></h1>
	                                    <time class="card-date">
							                <%= archive.created_at.strftime("%d %b, %Y")%>
	                                    </time>
	                                </div>
	                            </a>
	                        </article>
	                    </li>
	                <% end %>
                </ul>
                <div class="digg_pagination">
				  <%= will_paginate @all_archives, previous_label: "&lt;", next_label: "&gt;", :container => false %>
				</div> 
            </div>
    </main>
    <!--end l-main-->

app/views/blogs/edit.html.erb
<% provide(:title, "Editing Blog") %>
<%= render "partials/admin_navbar" %>

<!--start l-contents-->
<div class="l-container u-clear">
	<!--start l-main-->
	<main class="l-main js-main">
	    <div class="l-main-block"></div>

		<%= render 'form', blog: @blog %>
		<%= link_to blogs_path, class: "form-button" do %>
          <div class="button">
            <p class="button-text">Back</p>
          </div>
        <% end %> 
	</main>
	<!--end l-main-->
</div>
<!--end l-contents-->
  

app/views/blogs/index.html.erb
<% provide( :title, "Admin List")%>

  <!--start l-contents-->
<%= render "partials/admin_navbar" %>
  <div class="l-container u-clear">
      <!--start l-main-->
      <main class="l-main js-main">
          <div class="l-main-block"></div>
            <%= link_to new_blog_path, class: "l-main-button" do %>
              <div class="button">
                <p class="button-text">New Article</p>
              </div>
            <% end %>
          <ul class="archive archive-admin">
            <% @blogs.each do |blog| %>
              <li class="archive-item">
                <%= link_to edit_blog_path(blog), class: "post-article" do %>
                    <time class="post-article-date"><%= blog.created_at.strftime("%d %b, %Y")%></time>
                    <h1 class="post-article-title"><%= blog.title %></h1>
                <% end %>
              </li> 
            <% end %>
          </ul>
      </main>
      <!--end l-main-->
  </div> 

app/views/blogs/new.html.erb
<% provide(:title, "New Blog") %>
<%= render "partials/admin_navbar" %>

<!--start l-contents-->
<div class="l-container u-clear">
	<!--start l-main-->
	<main class="l-main js-main">
	    <div class="l-main-block"></div>

		<%= render 'form', blog: @blog %>
		<%= link_to blogs_path, class: "form-button" do %>
          <div class="button">
            <p class="button-text">Back</p>
          </div>
        <% end %> 
	</main>
	<!--end l-main-->
</div>
<!--end l-contents-->
 

app/views/blogs/show.html.erb
 <% provide(:title, @blog.title) %>
 <%= render "partials/user_navbar" %>

<!--start l-main-->
<main class="l-main js-main">
    <div class="l-main-block"></div>
    <div class="single">
    	<%= image_tag @blog.image.url(:medium), class: "single-image" %>
        <div class="l-container u-clear">
            <h1 class="single-title"><%= @blog.title %></h1>
            <time class="single-date"><%= @blog.created_at.strftime("%d %b, %Y")%></time>
            <p class="single-desc">
            	<%= @blog.content %>
            </p>
            <%= link_to root_path, class: "form-button" do %>
	          <div class="button">
	            <p class="button-text">Back</p>
	          </div>
	        <% end %> 
        </div>
    </div>

	<!--footer ここから-->
    <footer class="l-footer ">
    	
        <div class="l-footer-button">
	        <a class="page-top js-scroll" href="#js-body">
	            <span class="page-top-arrow"></span>
	        </a>
        </div>
    
    </footer>
    <!--footer ここまで-->
</main>
<!--end l-main-->  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 9]>
<html lang="ja" class="no-js lt-ie9" prefix="og: http://ogp.me/ns#">
<![endif]-->
<!--[if gt IE 9]><!-->
<html lang="ja" class="no-js" prefix="og: http://ogp.me/ns#"><!--<![endif]-->

<head>
    <meta charset="UTF-8">
    <title><%= full_title(yield(:title)) %></title>
    <meta name="description" content="sample text,sample tex">
    <meta name="keywords" content="word1,word2,word3">

    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta property="og:title" content="">
    <meta property="og:description" content="sample text,sample tex">
    <meta property="og:url" content="">
    <meta property="og:site_name" content="">
    <meta property="og:type" content="blog">
    <meta property="fb:admins" content="">
    <meta property="og:image" content="assets/images/common/ogp.png">

    <meta name="apple-mobile-web-app-title" content="">

    <link rel="shortcut icon" href="assets/images/common/favicon.ico">
    <link rel="apple-touch-icon-precomposed" href="images/common/apple-touch-icon-precomposed.png"> 
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body id="js-body">
    <div id="fb-root"></div>

    <noscript class="for-no-js">Javascriptを有効にしてください。</noscript>
    <div class="for-old">お使いのOS・ブラウザでは、本サイトを適切に閲覧できない可能性があります。最新のブラウザをご利用ください。</div>

    <input type="hidden" value="./" id="js-base-url">

    <div class="l-wrap js-wrap">
    

      <%= yield %>

      <!--footer ここから-->
      <footer class="l-footer l-footer-admin">
          
              <div class="l-footer-copyright">
               <small class="copyright">&copy;copyright</small>
              </div>
          
      </footer>
      <!--footer ここまで-->

    </div>

  </body>
    <%= javascript_include_tag 'modernizr' %>
    <%= javascript_include_tag 'app' %>

</html>

app/views/partials/_admin_navbar.html.erb
  <!--start header-->
  <header class="l-header l-header-admin js-header">
      <div class="l-header-top u-clear">
        <div class="l-header-logo">
          <%= link_to blogs_path, class: "logo" do %>
              <%= image_tag("logo-admin.png", width: "138", height: "28", alt: "BLOG")%>
          <% end %>  
        </div>
        <div class="l-header-text">
              <p>ADMIN PAGE</p>
              <% if current_admin %>
                 <p>(<%= link_to "Sign Out",destroy_admin_session_path, method: :delete %>)</p>
              <% end %>
        </div>
      </div>
  </header>
  <!--end header-->

app/views/partials/_user_navbar.html.erb
 <!--start header-->
<header class="l-header  js-header">
    <div class="l-header-top u-clear">
        <div class="l-header-logo">
            <%= link_to root_path, class: "logo" do %>
                <%= image_tag("logo.png", width: "253", height: "28", alt: "BLOG")%>
            <% end %> 
        </div>
        <div class="l-header-hamburger">
            <a href="#" class="hamburger js-hamburger " >
                <span class="hamburger-item"></span>
                <span class="hamburger-item"></span>
                <span class="hamburger-item"></span>
            </a>
        </div>
    </div>
</header>
<!--end header-->

<nav class="nav js-nav">
    <ul class="nav-list">
        <li class="nav-item">
            <%= link_to "TOP", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
            <%= link_to "Archive", archive_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
            <a href="#" class="nav-link">Facebook</a>
        </li>
        <li class="nav-item">
            <a href="#" class="nav-link">Twitter</a>
        </li>
    </ul>
</nav>